### ISSUE TITLE
PowerPointGenerator create_powerpoint() is not using the application's preferred model

### ISSUE THREAD

**Issue by pathbreak** [Width-ai/powerpoint-generative-ai#4]
The library allows apps to specify a preferred GPT-4 model in the constructor:

`
ppt_gen = PowerPointGenerator(openai_key="...", model="gpt-4-turbo-preview")
`

But `create_powerpoint()` does not use the app's preferred model:

`
deck_response = call_gpt_with_backoff(messages=deck_messages, temperature=0.2, max_length=MAX_CONTENT_LENGTH)
`

**Expected:**

It must respect the application's preference and pass the preferred model to `call_gpt_with_backoff()`:

`
deck_response = call_gpt_with_backoff(messages=deck_messages, model=self.model, temperature=0.2, max_length=MAX_CONTENT_LENGTH)
`

**Comment by pa-t** [comment]
Released new version with the change [here](https://pypi.org/project/powerpoint-generative-ai/0.1.8/)
